version: '3.8'
services:
  front:
    container_name: vue-client
    build:
      context: .
      dockerfile: front/Dockerfile
    volumes:
      - './front:/app'
      - 'node_modules:/usr/local/bundle'
    ports:
        - "5173:5173"
    tty: true
  backend:
    container_name: flask-api
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - './backend:/app'
    ports:
      - "8080:8080"
    tty: true
volumes:
  node_modules: